[workspace]
resolver = "2"
members = ["bytecode", "maru", "maru-file","refcounter"]

[workspace.dependencies]
bytecode = { path = "bytecode" }
maru-file = { path = "maru-file" }
refcounter = { path = "refcounter" }
